<!-- LOGO DIREITO -->
<a href="#"><img width="300px" src="http://www.universidadejava.com.br/images/2020-05-14-java-excecoes.png" align="right" /></a>

# Tratamento de exce√ß√µes

<p align="left">
  <a href="https://github.com/JonathanTSilva/HL-Java">
    <img src="https://img.shields.io/static/v1?label=HomeLab&message=Java&color=red&logo=java&logoColor=white&labelColor=grey&style=flat" alt="HL-Java">
  </a>
</p>

üîï Uma abordagem pr√°tica para entender o tratamento de exce√ß√µes no Java.

<!-- SUM√ÅRIO -->
- [Tratamento de exce√ß√µes](#tratamento-de-exce√ß√µes)
  - [1. Introdu√ß√£o](#1-introdu√ß√£o)
    - [1.1. Hierarquia de exce√ß√µes do Java](#11-hierarquia-de-exce√ß√µes-do-java)
  - [2. Estrutura try-catch](#2-estrutura-try-catch)
  - [3. Pilha de chamadas de m√©todos](#3-pilha-de-chamadas-de-m√©todos)
  - [4. Bloco `finally`](#4-bloco-finally)

<!-- VOLTAR AO IN√çCIO -->
<a href="#"><img width="40px" src="https://github.com/JonathanTSilva/JonathanTSilva/blob/main/Images/back-to-top.png" align="right" /></a>

## 1. Introdu√ß√£o

Para projetar uma boa solu√ß√£o de programa√ß√£o, √© necess√°rio conhecer qual a solu√ß√£o ruim para contornar tais problemas, come√ßando com uma solu√ß√£o muito ruim, posteriormente, apresentando melhorias, e por fim, chegando √† melhor solu√ß√£o, na qual foram tratadas todas as exce√ß√µes anteriormente encontradas.

Uma exce√ß√£o √© qualquer condi√ß√£o de erro ou comportamento inesperado encontrado por um programa em execu√ß√£o. Em Java, uma exce√ß√£o √© um objeto herdado da classe:

- `java.lang.Exception` - o compilador obriga a tratar ou propagar;
- `java.lang.RuntimeException` - o compilador n√£o obriga a tratar ou propagar.

Quando lan√ßada, uma exce√ß√£o √© propagada na pilha de chamadas de m√©todos em execu√ß√£o, at√© que seja capturada (tratada) ou o programa seja encerrado.

O tratamento de exce√ß√µes permite gerenciar os erros durante a execu√ß√£o de uma forma organizada. Assim, pode-se invocar uma rotina de tratamento de erro quando um erro ocorrer, pois fornece um meio de transferir o controle e as informa√ß√µes de um ponto na execu√ß√£o de um programa para um "tratador de exce√ß√µes" associado a um ponto previamente passado pela execu√ß√£o.

Um tratamento de exce√ß√µes pode ser usado para suportar no√ß√µes de tratamento de erros e computa√ß√£o tolerante a falhas.

O mecanismo de tratamento de exce√ß√µes requer o uso de tr√™s palavras chave: `try`, `catch` e `throw`. Nos termos mais gerais, os comandos de programa que devem ser monitorados para as exce√ß√µes est√£o contidos em um bloco de prova (try). Se uma exce√ß√£o (ou erro) ocorrer dentro do bloco de prova, ser√° disparada usando throw. A exce√ß√£o √© pega, usando catch, e processada.

Em suma, qualquer comando que dispara uma exce√ß√£o precisa ter sido executado dentro de um bloco try. Qualquer exce√ß√£o precisa ser pega por um comando catch que segue imediatamente o comando try que dispara a exce√ß√£o, isto √©, se uma exce√ß√£o √© chamada no bloco try, o controle do programa √© transferido para o gerenciador de exce√ß√£o apropriado. √â importante citar que as fun√ß√µes chamadas a partir de dentro de um bloco try tamb√©m podem disparar uma exce√ß√£o, e que o comando catch ir√° gerenciar qualquer exce√ß√£o, independente do tipo

O modelo de tratamento de exce√ß√µes permite que erros sejam tratados de forma consistente e flex√≠vel, usando boas pr√°ticas. Esse modelo apresenta as seguintes vantagens:

- Delega a l√≥gica do erro para a classe respons√°vel por conhecer as regras que podem ocasionar o erro;
- Trata de forma organizada (inclusive hier√°rquica) exce√ß√µes de tipos diferentes;
- A exce√ß√£o pode carregar dados quaisquer.

### 1.1. Hierarquia de exce√ß√µes do Java

Segue abaixo, uma amostra da hierarquia de exce√ß√µes do Java. Para maiores informa√ß√µes, visite a p√°gina da qual ela foi extra√≠da: [Hierarchy For Package java.lang][1], da Oracle.

![hie][A]

Tem-se uma superclass `Throwable` (classe gen√©rica de todas as exce√ß√µes e erros) e subclasses: `Error` (agrupa todos os erros que n√£o espera-se tratamento pelo programador) e `Exception`, cujo o programa tem a possibilidade do programa tratar (sendo que na `RuntimeException`, o compilador n√£o obriga a tratar os erros)

<!-- VOLTAR AO IN√çCIO -->
<a href="#"><img width="40px" src="https://github.com/JonathanTSilva/JonathanTSilva/blob/main/Images/back-to-top.png" align="right" /></a>

## 2. Estrutura try-catch

Como visto na introdu√ß√£o deste artigo, para tratar as exce√ß√µes em Java s√£o utilizados os comandos `try` e `catch`. Esses comandos apresentam a sintaxe abaixo:

```java
try {
 // Bloco de prova - inclui qualquer c√≥digo que pode chamar uma exce√ß√£o (throw)
} catch (ExceptionType arg) {
 // Executa algumas a√ß√µes
} catch (ExceptionType arg) {
 // Executa algumas a√ß√µes
} catch (ExceptionType arg) {
 // Executa algumas a√ß√µes
}
```

O bloco `try` cont√©m o c√≥digo que representa a execu√ß√£o normal do trecho de c√≥digo que pode acarretar em uma exce√ß√£o. Complementarmente, o bloco `catch` cont√©m o c√≥digo a ser executado caso uma exce√ß√£o ocorra. Deve ser especificado o tipo de exce√ß√£o a ser tratada (aqui, o *upcasting* √© permitido).

**Exemplo:**

```java
Scanner sc = new Scanner(System.in);

try {
  String[] vect = sc.nextLine().split(" ");
  int position = sc.nextInt(); // Uma das exce√ß√µes √© digitar uma letra ao inv√©s de um n√∫mero
  // ou, digitar uma posi√ß√£o que n√£o est√° dentro do limite do vetor
  System.out.println(vect[position]);
}
catch (ArrayIndexOutOfBoundsException e) {
  System.out.println("Invalid position");
}
catch (InputMismatchException e) {
  System.out.println("Input error");
}

System.out.println("End of program");

sc.close();
```

<!-- VOLTAR AO IN√çCIO -->
<a href="#"><img width="40px" src="https://github.com/JonathanTSilva/JonathanTSilva/blob/main/Images/back-to-top.png" align="right" /></a>

## 3. Pilha de chamadas de m√©todos

A pilha de chamadas (call stack) √© um mecanismo do interpretador de uma linguagem que organiza o funcionamento do script quando s√£o chamadas muitas fun√ß√µes, qual fun√ß√£o est√° sendo executada no momento, e quais ser√£o chamadas dentro de alguma fun√ß√£o, etc.

- Quando o script chama a fun√ß√£o, ela √© adicionada √† pilha de chamadas, e ent√£o √© iniciado o carregamento da fun√ß√£o.
- Qualquer fun√ß√£o chamada por essa fun√ß√£o ser√° adicionada √† pilha de chamadas uma acima da outra.
- Quando a fun√ß√£o termina a execu√ß√£o, o interpretador retira a fun√ß√£o da pilha e continua a execu√ß√£o do programa de onde parou.
- Caso a pilha ocupar mais espa√ßo do que foi separado a ela, ser√° exibido um erro "stack overflow" (estouro de pilha).

**Exemplo:**

```java
public class Program {
  public static void main(String[] args) {
    method1();
    System.out.println("End of program");
  }
  
  public static void method1() {
    System.out.println("*** METHOD1 START ***");
    method2();
    System.out.println("*** METHOD1 END ***");
  }

  public static void method2() {
    System.out.println("*** METHOD2 START ***");
    Scanner sc = new Scanner(System.in);
    try {
        String[] vect = sc.nextLine().split(" ");
        int position = sc.nextInt(); // Uma das exce√ß√µes √© digitar uma letra ao inv√©s de um n√∫mero
        // ou, digitar uma posi√ß√£o que n√£o est√° dentro do limite do vetor
        System.out.println(vect[position]);
    }
    catch (ArrayIndexOutOfBoundsException e) {
        System.out.println("Invalid position");
        e.printStackTrace(); // Imprime o tipo da exce√ß√£o, mensagem e a sequencia de chamadas que gerou a exe√ß√£o
        sc.next();
    }
    catch (InputMismatchException e) {
        System.out.println("Input error");
        e.printStackTrace();
    }
    sc.close();
    System.out.println("*** METHOD2 END ***");
  }  
}
```

<!-- VOLTAR AO IN√çCIO -->
<a href="#"><img width="40px" src="https://github.com/JonathanTSilva/JonathanTSilva/blob/main/Images/back-to-top.png" align="right" /></a>

## 4. Bloco `finally`

√â um bloco que cont√©m c√≥digo a ser executado independentemente de ter ocorrido ou n√£o uma exce√ß√£o.

Um exemplo cl√°ssico para ilustrar a aplica√ß√£o deste bloco √©: fechar um arquivo, conex√£o com o banco de dados, ou outro recurso espec√≠fico ao final do processamento.

```java
try{

} catch(ExceptionType e) {

} finally {

}
```

**Exemplo:**

```java
package application;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class Program1 {
  public static void main(String[] args) {
    File file = new File("C:\\temp\\in.txt");
    Scanner sc = null;
    try {
      sc = new Scanner(file);
      while (sc.hasNextLine()) {
        System.out.println(sc.nextLine());
      }
    } catch (IOException e) {
      System.out.println("Error opening file: " + e.getMessage());
    } finally { // √â executado independentemente do sucesso ou n√£o do try
      if (sc != null) {
        sc.close();
      }
    }
  }
}
```

<!-- MARKDOWN LINKS -->
<!-- SITES -->
[1]: https://docs.oracle.com/javase/8/docs/api/java/lang/package-tree.html

<!-- IMAGES -->
[A]: ../../Images/exceptionHie.png
